// Code generated by mockery. DO NOT EDIT.

package automock

import (
	db_error "awesomeProject/library-app/global/db_error"

	mock "github.com/stretchr/testify/mock"

	models "awesomeProject/library-app/models"

	uuid "github.com/google/uuid"
)

// AuthorManager is an autogenerated mock type for the AuthorManager type
type AuthorManager struct {
	mock.Mock
}

type AuthorManager_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthorManager) EXPECT() *AuthorManager_Expecter {
	return &AuthorManager_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0
func (_m *AuthorManager) Create(_a0 models.Author) (models.Author, *db_error.DBError) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Author
	var r1 *db_error.DBError
	if rf, ok := ret.Get(0).(func(models.Author) (models.Author, *db_error.DBError)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(models.Author) models.Author); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.Author)
	}

	if rf, ok := ret.Get(1).(func(models.Author) *db_error.DBError); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*db_error.DBError)
		}
	}

	return r0, r1
}

// AuthorManager_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AuthorManager_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 models.Author
func (_e *AuthorManager_Expecter) Create(_a0 interface{}) *AuthorManager_Create_Call {
	return &AuthorManager_Create_Call{Call: _e.mock.On("Create", _a0)}
}

func (_c *AuthorManager_Create_Call) Run(run func(_a0 models.Author)) *AuthorManager_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.Author))
	})
	return _c
}

func (_c *AuthorManager_Create_Call) Return(_a0 models.Author, _a1 *db_error.DBError) *AuthorManager_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorManager_Create_Call) RunAndReturn(run func(models.Author) (models.Author, *db_error.DBError)) *AuthorManager_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: _a0
func (_m *AuthorManager) Delete(_a0 uuid.UUID) (models.Author, *db_error.DBError) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 models.Author
	var r1 *db_error.DBError
	if rf, ok := ret.Get(0).(func(uuid.UUID) (models.Author, *db_error.DBError)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) models.Author); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.Author)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) *db_error.DBError); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*db_error.DBError)
		}
	}

	return r0, r1
}

// AuthorManager_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type AuthorManager_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - _a0 uuid.UUID
func (_e *AuthorManager_Expecter) Delete(_a0 interface{}) *AuthorManager_Delete_Call {
	return &AuthorManager_Delete_Call{Call: _e.mock.On("Delete", _a0)}
}

func (_c *AuthorManager_Delete_Call) Run(run func(_a0 uuid.UUID)) *AuthorManager_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *AuthorManager_Delete_Call) Return(_a0 models.Author, _a1 *db_error.DBError) *AuthorManager_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorManager_Delete_Call) RunAndReturn(run func(uuid.UUID) (models.Author, *db_error.DBError)) *AuthorManager_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: _a0
func (_m *AuthorManager) Get(_a0 uuid.UUID) (models.Author, *db_error.DBError) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.Author
	var r1 *db_error.DBError
	if rf, ok := ret.Get(0).(func(uuid.UUID) (models.Author, *db_error.DBError)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) models.Author); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.Author)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) *db_error.DBError); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*db_error.DBError)
		}
	}

	return r0, r1
}

// AuthorManager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type AuthorManager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 uuid.UUID
func (_e *AuthorManager_Expecter) Get(_a0 interface{}) *AuthorManager_Get_Call {
	return &AuthorManager_Get_Call{Call: _e.mock.On("Get", _a0)}
}

func (_c *AuthorManager_Get_Call) Run(run func(_a0 uuid.UUID)) *AuthorManager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *AuthorManager_Get_Call) Return(_a0 models.Author, _a1 *db_error.DBError) *AuthorManager_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorManager_Get_Call) RunAndReturn(run func(uuid.UUID) (models.Author, *db_error.DBError)) *AuthorManager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields:
func (_m *AuthorManager) GetAll() ([]models.Author, *db_error.DBError) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Author
	var r1 *db_error.DBError
	if rf, ok := ret.Get(0).(func() ([]models.Author, *db_error.DBError)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Author); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Author)
		}
	}

	if rf, ok := ret.Get(1).(func() *db_error.DBError); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*db_error.DBError)
		}
	}

	return r0, r1
}

// AuthorManager_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type AuthorManager_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *AuthorManager_Expecter) GetAll() *AuthorManager_GetAll_Call {
	return &AuthorManager_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *AuthorManager_GetAll_Call) Run(run func()) *AuthorManager_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthorManager_GetAll_Call) Return(_a0 []models.Author, _a1 *db_error.DBError) *AuthorManager_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorManager_GetAll_Call) RunAndReturn(run func() ([]models.Author, *db_error.DBError)) *AuthorManager_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0
func (_m *AuthorManager) Update(_a0 models.Author) (models.Author, *db_error.DBError) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.Author
	var r1 *db_error.DBError
	if rf, ok := ret.Get(0).(func(models.Author) (models.Author, *db_error.DBError)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(models.Author) models.Author); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.Author)
	}

	if rf, ok := ret.Get(1).(func(models.Author) *db_error.DBError); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*db_error.DBError)
		}
	}

	return r0, r1
}

// AuthorManager_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type AuthorManager_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 models.Author
func (_e *AuthorManager_Expecter) Update(_a0 interface{}) *AuthorManager_Update_Call {
	return &AuthorManager_Update_Call{Call: _e.mock.On("Update", _a0)}
}

func (_c *AuthorManager_Update_Call) Run(run func(_a0 models.Author)) *AuthorManager_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.Author))
	})
	return _c
}

func (_c *AuthorManager_Update_Call) Return(_a0 models.Author, _a1 *db_error.DBError) *AuthorManager_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorManager_Update_Call) RunAndReturn(run func(models.Author) (models.Author, *db_error.DBError)) *AuthorManager_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthorManager creates a new instance of AuthorManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorManager {
	mock := &AuthorManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
