// Code generated by mockery. DO NOT EDIT.

package automock

import (
	structs "awesomeProject/todo-app/structs"

	mock "github.com/stretchr/testify/mock"
)

// TagManager is an autogenerated mock type for the TagManager type
type TagManager struct {
	mock.Mock
}

type TagManager_Expecter struct {
	mock *mock.Mock
}

func (_m *TagManager) EXPECT() *TagManager_Expecter {
	return &TagManager_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0
func (_m *TagManager) Create(_a0 structs.Tag) (structs.Tag, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 structs.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(structs.Tag) (structs.Tag, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(structs.Tag) structs.Tag); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(structs.Tag)
	}

	if rf, ok := ret.Get(1).(func(structs.Tag) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TagManager_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TagManager_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 structs.Tag
func (_e *TagManager_Expecter) Create(_a0 interface{}) *TagManager_Create_Call {
	return &TagManager_Create_Call{Call: _e.mock.On("Create", _a0)}
}

func (_c *TagManager_Create_Call) Run(run func(_a0 structs.Tag)) *TagManager_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(structs.Tag))
	})
	return _c
}

func (_c *TagManager_Create_Call) Return(_a0 structs.Tag, _a1 error) *TagManager_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TagManager_Create_Call) RunAndReturn(run func(structs.Tag) (structs.Tag, error)) *TagManager_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: _a0
func (_m *TagManager) Delete(_a0 string) (structs.Tag, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 structs.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (structs.Tag, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) structs.Tag); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(structs.Tag)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TagManager_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TagManager_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - _a0 string
func (_e *TagManager_Expecter) Delete(_a0 interface{}) *TagManager_Delete_Call {
	return &TagManager_Delete_Call{Call: _e.mock.On("Delete", _a0)}
}

func (_c *TagManager_Delete_Call) Run(run func(_a0 string)) *TagManager_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TagManager_Delete_Call) Return(_a0 structs.Tag, _a1 error) *TagManager_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TagManager_Delete_Call) RunAndReturn(run func(string) (structs.Tag, error)) *TagManager_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: _a0
func (_m *TagManager) Get(_a0 string) (structs.Tag, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 structs.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (structs.Tag, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) structs.Tag); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(structs.Tag)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TagManager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TagManager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 string
func (_e *TagManager_Expecter) Get(_a0 interface{}) *TagManager_Get_Call {
	return &TagManager_Get_Call{Call: _e.mock.On("Get", _a0)}
}

func (_c *TagManager_Get_Call) Run(run func(_a0 string)) *TagManager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TagManager_Get_Call) Return(_a0 structs.Tag, _a1 error) *TagManager_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TagManager_Get_Call) RunAndReturn(run func(string) (structs.Tag, error)) *TagManager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields:
func (_m *TagManager) GetAll() []structs.Tag {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []structs.Tag
	if rf, ok := ret.Get(0).(func() []structs.Tag); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]structs.Tag)
		}
	}

	return r0
}

// TagManager_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type TagManager_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *TagManager_Expecter) GetAll() *TagManager_GetAll_Call {
	return &TagManager_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *TagManager_GetAll_Call) Run(run func()) *TagManager_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TagManager_GetAll_Call) Return(_a0 []structs.Tag) *TagManager_GetAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TagManager_GetAll_Call) RunAndReturn(run func() []structs.Tag) *TagManager_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewTagManager creates a new instance of TagManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTagManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TagManager {
	mock := &TagManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
