// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID              string    `json:"id"`
	Title           string    `json:"title"`
	Year            int32     `json:"year"`
	Author          string    `json:"author"`
	Category        *Category `json:"category"`
	TotalCopies     int32     `json:"totalCopies"`
	AvailableCopies int32     `json:"availableCopies"`
	Language        string    `json:"language"`
}

type Category struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
